id: CO2_test_2
name: Office
location: Office_
collection: sensorData
password: azmZ8^G4u!7Ejo
email: SensorDemoWoonkamer@tropicaltrading.nl
firebase rest url: https://identitytoolkit.googleapis.com/v1/accounts
firebase api key: AIzaSyCkjz9EwEC3ssB6ly-2andv5Gbvi9nDyjY